student:
  age: 23
  name: xiao
  address: gree
  maps: {1: lanqiu , 2: zuqiu}

server:
  port: 8888

spring:
  redis:
    password: xiao9616
    port: 6379
    host: 172.28.4.109
    jedis:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 6
    timeout: 2000